config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'time_entries#index'

  resources :time_entries, only: %i[index edit update] do
    collection do
      post :start_timer 
      put :stop_timer
    end  
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :user

  validates :starts_at, presence: true
  validates :finishes_at, presence: true, if: -> { self.persisted? }
  validate :only_one_running, if: -> { self.new_record? } 

  private

  def only_one_running
    errors.add(:running, 'already running') if user&.timer_running?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :time_entries, dependent: :destroy

  def current_timer
    time_entries.find_by(finishes_at: nil)
  end  

  def timer_running?
    current_timer.present?
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_time_entry, only: %i[edit update]

  def index
    @time_entries = current_user.time_entries.order(id: :desc)
  end

  def edit
  end

  def update
    @time_entry.edited = true
    if @time_entry.update(time_entry_params)
      redirect_to time_entries_path, notice: "Time entry was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def start_timer
    @time_entry = current_user.time_entries.new(starts_at: Time.now)
    if @time_entry.save
      flash[:notice] = "Timer was successfully started"
    else
      flash[:notice] = "Timer can't be started"
    end
    redirect_to time_entries_path
  end

  def stop_timer
    @time_entry = current_user.current_timer
    if @time_entry && @time_entry.update(finishes_at: Time.now)
      flash[:notice] = "Timer was successfully stopped"
    else
      flash[:notice] = "Timer can't be stopped"
    end  
    redirect_to time_entries_path
  end

  private
    def set_time_entry
      @time_entry = current_user.time_entries.find(params[:id])
    end

    def time_entry_params
      params.require(:time_entry).permit(:starts_at, :finishes_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formated_time(time, filling = 'None')
    return filling unless time
    time.strftime('%Y-%m-%d %I:%M %p')
  end 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainualTimer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>

    <%= yield %>
  </body>
</html>

app/views/time_entries/_clock_in_button.erb
<%= link_to 'Clock In', start_timer_time_entries_path, method: :post %>

app/views/time_entries/_clock_out_button.erb
<%= link_to 'Clock Out', stop_timer_time_entries_path, method: :put %>

app/views/time_entries/_form.html.erb
<%= form_with(model: time_entry, local: true) do |form| %>
  <% if time_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_entry.errors.count, "error") %> prohibited this time_entry from being saved:</h2>

      <ul>
        <% time_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

      
    </div>
  <% end %>
  
  <div>
    <%= form.datetime_field :starts_at %>
  </div>  

  <div>
    <%= form.datetime_field :finishes_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_entries/edit.html.erb
<h1>Editing Time Entry</h1>

<%= render 'form', time_entry: @time_entry %>

<%= link_to 'Back', time_entries_path %>

app/views/time_entries/index.html.erb
<p id="notice"><%= notice %></p>

<div id="timer-button">
  <% if current_user.timer_running? %>
    <%= render 'clock_out_button.erb' %>
  <% else %>
    <%= render 'clock_in_button.erb' %>
  <% end %>
</div>


<h1>Your times</h1>

<table>
  <thead>
    <tr>
      <th>Starts At</th>
      <th>Finishes At</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @time_entries.each do |time_entry| %>
      <tr>
        <td><%= formated_time(time_entry.starts_at) %></td>
        <td><%= formated_time(time_entry.finishes_at, 'Running...') %></td>
        <td>
          <% if time_entry.finishes_at %>
            <%= link_to 'Edit', edit_time_entry_path(time_entry) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>